package net.kleditzsch.smarthome.model.settings.Interface;

/**
 * Einstellungen
 */
public enum Settings {

    //Globale Einstellungen
    SERVER_PORT,
    SERVER_SECURE_PORT,
    SERVER_KEY_STORE_PASSWORD,
    SERVER_KEY_MANAGER_PASSWORD,
    BACKUP_ENABLE_AUTO_BACKUP,
    BACKUP_AUTO_CLEANUP_DAYS,
    BACKUP_AUTO_SUCCESS_MAIL,
    BACKUP_AUTO_ERROR_MAIL,
    BACKUP_FTP_UPLOAD,
    BACKUP_FTP_UPLOAD_HOST,
    BACKUP_FTP_UPLOAD_PORT,
    BACKUP_FTP_UPLOAD_SECURE_TYPE,
    BACKUP_FTP_UPLOAD_USER,
    BACKUP_FTP_UPLOAD_PASSWORD,
    BACKUP_FTP_UPLOAD_DIRECTORY,
    MAIL_HOST,
    MAIL_PORT,
    MAIL_SECURE_TYPE,
    MAIL_USER,
    MAIL_PASSWORD,
    MAIL_RECEIVER_ADDRESS,

    //SmartHome Einstellungen
    AUTOMATION_SUNRISE_OFFSET,
    AUTOMATION_SUNSET_OFFSET,
    AUTOMATION_LATITUDE,
    AUTOMATION_LONGITUDE,
    AUTOMATION_FB_ACTIVE,
    AUTOMATION_FB_ADDRESS,
    AUTOMATION_FB_USER,
    AUTOMATION_FB_PASSWORD,
    AUTOMATION_ENERGY_ELECTRIC_PRICE,
    AUTOMATION_ENERGY_WATER_PRICE,
    AUTOMATION_PAGNATION_ELEMENTS_AT_PAGE,
    AUTOMATION_MQTT_ACTIVE,
    AUTOMATION_MQTT_BROKER_ADDRESS,
    AUTOMATION_MQTT_BROKER_PORT,
    AUTOMATION_MQTT_BROKER_CLIENT_ID,
    AUTOMATION_MQTT_BROKER_USERNAME,
    AUTOMATION_MQTT_BROKER_PASSWORD,

    //Filme Einstellungen
    MOVIE_PAGINATION_ELEMENTS_AT_ADMIN_PAGE,
    MOVIE_PAGINATION_ELEMENTS_AT_USER_PAGE,
    MOVIE_NEWEST_MOVIES_COUNT,
    MOVIE_BEST_MOVIES_COUNT,
    MOVIE_TMDB_API_KEY,

    //Netzwerk Einstellungen
    NETWORK_PRINTER_STATE_IP,
    NETWORK_NAS_STATE_IP,

    //Rezepte Einstellungen
    RECIPE_PAGINATION_ELEMENTS_AT_ADMIN_PAGE,
    RECIPE_PAGINATION_ELEMENTS_AT_USER_PAGE,
    RECIPE_NEWEST_RECIPE_COUNT,
    RECIPE_SHOPPING_LIST_ID,

    //Kontakte
    CONTACT_PAGINATION_ELEMENTS_AT_USER_PAGE
}
